
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.JSType;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wildan
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        getMenu();
        pilihMenu();
        hargaMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldPembeli = new javax.swing.JTextField();
        jComboBoxMenu = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBayar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextMenu = new javax.swing.JTextField();
        jTextHarga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton3.setText("Laporan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 240, 90, 30);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 240, 51, 30);

        jPanel1.setLayout(null);

        jTextFieldPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPembeliActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPembeli);
        jTextFieldPembeli.setBounds(120, 10, 180, 30);

        jComboBoxMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMenuActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxMenu);
        jComboBoxMenu.setBounds(120, 50, 180, 30);

        jLabel1.setText("Pembeli");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 70, 14);

        jLabel2.setText("Pesanan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 50, 60, 14);

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(230, 150, 70, 30);

        jLabel6.setText("Harga");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 90, 50, 14);

        jLabelHarga.setText("Rp 0");
        jPanel1.add(jLabelHarga);
        jLabelHarga.setBounds(120, 90, 180, 14);

        jLabel8.setText("Bayar");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 110, 60, 14);

        jTextFieldBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBayarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBayar);
        jTextFieldBayar.setBounds(120, 110, 180, 30);

        jTabbedPane3.addTab("Transaksi", jPanel1);

        jPanel3.setLayout(null);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(230, 150, 70, 30);

        jLabel4.setText("Menu");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 40, 60, 14);

        jLabel5.setText("Harga");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 80, 60, 14);
        jPanel3.add(jTextMenu);
        jTextMenu.setBounds(120, 40, 180, 30);

        jTextHarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextHarga);
        jTextHarga.setBounds(120, 80, 180, 30);

        jTabbedPane3.addTab("Menu", jPanel3);

        getContentPane().add(jTabbedPane3);
        jTabbedPane3.setBounds(0, 60, 340, 210);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESTO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 20, 120, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -10, 400, 100);

        setSize(new java.awt.Dimension(346, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextFieldPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPembeliActionPerformed

    private void jComboBoxMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMenuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new Laporan().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String menu = jTextMenu.getText();
        String harga = jTextHarga.getText();
        
        if("".equals(menu) || "".equals(harga)) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int iharga = Integer.parseInt(harga);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Harga harus angka", "Error", JOptionPane.WARNING_MESSAGE);
                jTextHarga.setText("");
                return;
            }
            
            String SQL = "INSERT INTO `menu`(`nama`,`harga`) VALUES('"+menu+"',"+harga+")";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Menu berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                getMenu();
                jTextMenu.setText("");
                jTextHarga.setText("");
            } else {
                JOptionPane.showMessageDialog(this,"Menu gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);   
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBayarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String pembeli = jTextFieldPembeli.getText();
        String bayar = jTextFieldBayar.getText();
        String pesanan = (String) jComboBoxMenu.getSelectedItem();
        int harga = Integer.parseInt(hargaMenu());
        
        if("".equals(pembeli) || "".equals(jTextFieldBayar.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int ibayar = Integer.parseInt(bayar);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, "Bayar harus angka", "Error", JOptionPane.WARNING_MESSAGE);
                jTextHarga.setText("");
                return;
            }
            int ibayar = Integer.parseInt(bayar);
            int kembali = 0;
            if(ibayar > harga) {
                kembali = ibayar-harga;
            } else if(harga > ibayar) {
                JOptionPane.showMessageDialog(this, "Uang tidak cukup", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
            Date tanggal = new Date();
            
            String SQL = "INSERT INTO `transaksi`(`tanggal`,`pembeli`,`pesanan`,`bayar`,`harga`,`kembali`) VALUES('"+dateFormat.format(tanggal)+"','"+pembeli+"','"+pesanan+"',"+bayar+","+harga+","+kembali+")";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Transaksi berhasil\nKembali: Rp "+kembali, "Sukses", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldBayar.setText("");
                jTextFieldPembeli.setText("");
            } else {
                JOptionPane.showMessageDialog(this,"Transaksi gagal", "Gagal", JOptionPane.WARNING_MESSAGE);   
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void getMenu() {
        String SQL = "SELECT * FROM `menu`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            jComboBoxMenu.removeAllItems();
            while(rs.next()) {
                String nama = rs.getString(2);
                jComboBoxMenu.addItem(nama);
            }
        } catch (SQLException ex){
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBoxMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextFieldBayar;
    private javax.swing.JTextField jTextFieldPembeli;
    private javax.swing.JTextField jTextHarga;
    private javax.swing.JTextField jTextMenu;
    // End of variables declaration//GEN-END:variables

    private void pilihMenu() {
        jComboBoxMenu.addActionListener (new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent ae) {
                hargaMenu();
            }
        });
    }
    
    private String hargaMenu() {
        String selected = (String) jComboBoxMenu.getSelectedItem();
        
        String SQL = "SELECT `harga` FROM `menu` WHERE nama='"+selected+"'";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        String harga = "";
        try {
            while(rs.next())
                harga = rs.getString(1);
        } catch (SQLException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabelHarga.setText("Rp "+harga);
        return harga;
    }
}
